name: Rust

on:
  push:
    branches: 
      - master 
  pull_request:
    branches: 
      - master
  schedule:
    - cron: "27 7 11 * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: cargo check --all-targets
    - name: Test
      run: cargo test
    - name: Format 
      run: cargo fmt -- --check
